---
apiVersion: v1
kind: Service
metadata:
  name: blizz-server
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: blizz-server-test