apiVersion: apps/v1
kind: Deployment
metadata:
  name: blizz-server-{{BLIZZ_VERSION}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blizz-server-{{BLIZZ_VERSION}}
  template:
    metadata:
      labels:
        app: blizz-server-{{BLIZZ_VERSION}}
    spec:
      containers:     
      - name: blizz-server
        image: docker.io/shreyasgune/blizz-server:{{BLIZZ_VERSION}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_ADDR
            valueFrom:
              configMapKeyRef:
                  name: app-configmap # name of the config-map
                  key: redis-service # import the value of 'redis-service' from app-configmap
        livenessProbe:
          httpGet:
            path: /version
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3