apiVersion: v1
kind: Service
metadata:
  name: blizz-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 443
    protocol: TCP
    targetPort: 8080
    name: https
  selector:
    app: blizz-server-{{BLIZZ_VERSION}}