name: GKE Terraform Deploy
on: [pull_request]

jobs:
  GKE-deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SGUNE_TERRAFORM_SA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: gke-tf

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: gke-tf
          variables:
            access_token = "${{ secrets.SGUNE_TERRAFORM_SA }}"