name: Minikube Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'     
        required: true
        default: test

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    name: Find image and deploy
    steps:
    - uses: actions/checkout@v2

    - name: replace the version_number in deployment yaml
      run: sed -in 's/{{BLIZZ_VERSION}}/${{ github.event.inputs.version }}/g' k8s/deployment.yaml

    - name: replace the version_number in svc yaml
      run: sed -in 's/{{BLIZZ_VERSION}}/${{ github.event.inputs.version }}/g' k8s/svc.yaml

    - name: verify the substituion
      run: cat k8s/deployment.yaml | grep "image"

    - name: Start minikube
      uses: medyagh/setup-minikube@master 

    - name: Deploy to minikube
      run: 
        kubectl apply -f k8s
  
    - name: Get List of Pods
      run: kubectl get pods

    - name: Get List of Services
      run: kubectl get svc 

    - name: Test service URLs
      run: |
        sleep 4 
        minikube service blizz-server --url
        echo -n "\n------------------opening the service------------------\n"
        sleep 10
        curl $(minikube service blizz-server --url)/version
