name: Security Scan

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'     
        required: true
        default: test

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Build a Docker image
        run: docker build -t temp/test .
        
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: false
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: temp/test
          args: --file=Dockerfile
        
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      
      - name: Scan Remote image
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: "docker.io/shreyasgune/blizz-server:${{ github.event.inputs.version }}"


