name: Security Scan

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'     
        required: true
        default: test

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "docker.io/shreyasgune/blizz-server:${{ github.event.inputs.version }}"



