name: Security Scan

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'     
        required: true
        default: test

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: "docker.io/shreyasgune/blizz-server:${{ github.event.inputs.version }}"
          sarif: true
     
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif


