name: Image Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'     
        required: true
        default: test

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    services:
      blizz-server:
        image: docker.io/shreyasgune/blizz-server:${{ github.event.inputs.version }}
        ports:
          - 8080:8080
    steps:
      - name: test the curl
        run: sleep 5 && curl localhost:8080/version 



